-- ====================================================================
-- SIGPA — Sistema de Gestión de Prácticas Académicas (UDI)
-- Script de Creación y Sincronización del Esquema de Base de Datos
-- Motor: Oracle Database 10g / 11g / 19c / 23c
-- ====================================================================

-- ── 1. Eliminar Triggers si existen ─────────────────────────────────
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER TRG_BITACORA_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ASIGNACION_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PRACTICA_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER TRG_USUARIO_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ── 2. Eliminar Secuencias si existen ───────────────────────────────
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BITACORA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ASIGNACION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRACTICA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ── 3. Eliminar Tablas si existen (Orden por dependencias FK) ────────
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BITACORA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ASIGNACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PRACTICA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ── 4. Creación de Secuencias ───────────────────────────────────────
CREATE SEQUENCE SEQ_USUARIO    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRACTICA   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ASIGNACION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BITACORA   START WITH 1 INCREMENT BY 1 NOCACHE;

-- ── 5. Creación de Tablas ───────────────────────────────────────────

-- 5.1 Tabla USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO   NUMBER(10) PRIMARY KEY,
    NOMBRE       VARCHAR2(100) NOT NULL,
    APELLIDO     VARCHAR2(100),
    EMAIL        VARCHAR2(150) UNIQUE NOT NULL,
    CONTRASENA   VARCHAR2(255) NOT NULL,
    ROL          VARCHAR2(30) NOT NULL CHECK (ROL IN ('DIRECTOR', 'COORDINADOR', 'ESTUDIANTE', 'TUTOR', 'ASESOR')),
    ACTIVO       VARCHAR2(10) DEFAULT 'S' CHECK (ACTIVO IN ('S', 'N'))
);

-- 5.2 Tabla PRACTICA
CREATE TABLE PRACTICA (
    ID_PRACTICA  NUMBER(10) PRIMARY KEY,
    NOMBRE       VARCHAR2(150) NOT NULL,
    ESTADO       VARCHAR2(20) DEFAULT 'ABIERTA' CHECK (ESTADO IN ('ABIERTA', 'CERRADA'))
);

-- 5.3 Tabla ASIGNACION (Gestión y vinculación de estudiantes a prácticas)
CREATE TABLE ASIGNACION (
    ID_ASIGNACION      NUMBER(10) PRIMARY KEY,
    ID_PRACTICA        NUMBER(10) NOT NULL,
    ID_ESTUDIANTE      NUMBER(10) NOT NULL,
    ESTADO_APROBACION  VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (ESTADO_APROBACION IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    CONSTRAINT FK_ASIG_PRACTICA   FOREIGN KEY (ID_PRACTICA)   REFERENCES PRACTICA(ID_PRACTICA),
    CONSTRAINT FK_ASIG_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIO(ID_USUARIO)
);

-- 5.4 Tabla BITACORA (Registro de visitas, horas y evidencias)
CREATE TABLE BITACORA (
    ID_BITACORA    NUMBER(10) PRIMARY KEY,
    ID_ASIGNACION  NUMBER(10) NOT NULL,
    FECHA          DATE NOT NULL,
    HORAS          NUMBER(4) NOT NULL,
    DESCRIPCION    VARCHAR2(500) NOT NULL,
    URL_EVIDENCIA  VARCHAR2(200),
    CONSTRAINT FK_BITACORA_ASIG FOREIGN KEY (ID_ASIGNACION) REFERENCES ASIGNACION(ID_ASIGNACION)
);

-- ── 6. Triggers para Autoincremento Automático (Patrón Oracle 10g) ───
CREATE OR REPLACE TRIGGER TRG_USUARIO_ID
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_USUARIO IS NULL THEN
        SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRACTICA_ID
BEFORE INSERT ON PRACTICA
FOR EACH ROW
BEGIN
    IF :NEW.ID_PRACTICA IS NULL THEN
        SELECT SEQ_PRACTICA.NEXTVAL INTO :NEW.ID_PRACTICA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ASIGNACION_ID
BEFORE INSERT ON ASIGNACION
FOR EACH ROW
BEGIN
    IF :NEW.ID_ASIGNACION IS NULL THEN
        SELECT SEQ_ASIGNACION.NEXTVAL INTO :NEW.ID_ASIGNACION FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BITACORA_ID
BEFORE INSERT ON BITACORA
FOR EACH ROW
BEGIN
    IF :NEW.ID_BITACORA IS NULL THEN
        SELECT SEQ_BITACORA.NEXTVAL INTO :NEW.ID_BITACORA FROM DUAL;
    END IF;
END;
/

-- ── 7. Inserción de Datos Iniciales (Seed Data) ─────────────────────
-- Contraseña por defecto para todos los usuarios de prueba: '1234' cifrada con bcrypt ($2b$10$...)

-- Usuarios con cada rol del sistema SIGPA
INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, ROL, ACTIVO)
VALUES (SEQ_USUARIO.NEXTVAL, 'Directora General', 'UDI', 'director@sigpa.edu', '$2b$10$bOrLbbmzQrt3RU7SV/zUceAVhV3vgdkMjAv9qGV8SFJDqkbmJDf7.', 'DIRECTOR', 'S');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, ROL, ACTIVO)
VALUES (SEQ_USUARIO.NEXTVAL, 'Laura Practicante', 'Estudiante', 'estudiante@sigpa.edu', '$2b$10$bOrLbbmzQrt3RU7SV/zUceAVhV3vgdkMjAv9qGV8SFJDqkbmJDf7.', 'ESTUDIANTE', 'S');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, ROL, ACTIVO)
VALUES (SEQ_USUARIO.NEXTVAL, 'Tutor UDI', 'Sistema', 'tutor@sigpa.edu', '$2b$10$bOrLbbmzQrt3RU7SV/zUceAVhV3vgdkMjAv9qGV8SFJDqkbmJDf7.', 'TUTOR', 'S');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, ROL, ACTIVO)
VALUES (SEQ_USUARIO.NEXTVAL, 'Asesora de Práctica', 'Sistema', 'asesor@sigpa.edu', '$2b$10$bOrLbbmzQrt3RU7SV/zUceAVhV3vgdkMjAv9qGV8SFJDqkbmJDf7.', 'ASESOR', 'S');

-- Prácticas académicas
INSERT INTO PRACTICA (ID_PRACTICA, NOMBRE, ESTADO)
VALUES (SEQ_PRACTICA.NEXTVAL, 'Práctica Observación Nivel 1', 'ABIERTA');

INSERT INTO PRACTICA (ID_PRACTICA, NOMBRE, ESTADO)
VALUES (SEQ_PRACTICA.NEXTVAL, 'Práctica Intervención Nivel 2', 'ABIERTA');

-- Asignación de prueba (Estudiante Laura a Práctica 1)
INSERT INTO ASIGNACION (ID_ASIGNACION, ID_PRACTICA, ID_ESTUDIANTE, ESTADO_APROBACION)
VALUES (SEQ_ASIGNACION.NEXTVAL, 1, 3, 'APROBADA');

-- Bitácora de prueba (Registro inicial de 4 horas)
INSERT INTO BITACORA (ID_BITACORA, ID_ASIGNACION, FECHA, HORAS, DESCRIPCION, URL_EVIDENCIA)
VALUES (SEQ_BITACORA.NEXTVAL, 1, SYSDATE - 5, 4, 'Observación en aula de clase', 'http://drive.link/foto1');

COMMIT;
